version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: padz_postgres
    restart: always
    environment:
      POSTGRES_USER: padz_user
      POSTGRES_PASSWORD: padz_password
      POSTGRES_DB: padz_db
    ports:
      - "5432:5432"
    volumes:
      - padz_pgdata:/var/lib/postgresql/data

volumes:
  padz_pgdata:
